### ISSUE TITLE
Multi Page Selector Attribute :: Concrete 5 8.2 RC2

### ISSUE THREAD

**Issue by benmlister** [Mesuva/multi_page_selector_attribute#1]
Cannot use this attribute in single page mode.

Argument 4 passed to Concrete\Core\Form\Service\Widget\PageSelector::selectFromSitemap() must be an instance of Concrete\Core\Entity\Site\SiteTree, array given, called in /packages/multi_page_selector_attribute/attributes/multi_page_selector/controller.php on line 72

**Comment by Mesuva** [comment]
When you say single page mode, do you mean a single page?

Does it work in general if added to any regular page?

**Comment by benmlister** [comment]
It works correctly with 5.8.1 but not with 5.8.2

When setting up the attribute you have the option to select restrictions. One of the restrictions is the ability to select a single page instead of multiple pages.

I get the above error message when having the restriction set to **Single Page Selection Only**, error goes away when it isn't selected.
![screen shot 2017-06-30 at 2 07 14 pm](https://user-images.githubusercontent.com/9346525/27720630-f3f0f8b6-5d9d-11e7-80d0-020972a672fa.png)

**Comment by Mesuva** [comment]
Oh sorry, now I remember that option!

I'll try to investigate

**Comment by benmlister** [comment]
Thanks heaps Ryan.

Also, how hard would it be to return the page values in the composer form as a select list instead of a topic tree list? I'm thinking to save screen realestate.

Might be able to tweak it on my end as a trial.

Cheers
Ben

**Comment by Mesuva** [comment]
I've pushed up a simple update to address this bug, let me know how you go.

With the select list I'm sure this would be possible, but I'm a bit tight on time at the moment to look into it. If you do happen to work out a solution I'm happy to review and merge a PR.

**Comment by benmlister** [comment]
Thanks mate
