### ISSUE TITLE
Add page to attribute programatically?

### ISSUE THREAD

**Issue by eskema** [Mesuva/multi_page_selector_attribute#3]
Hi Mesuva,

I need to add this attribute programmatically, how can it be done?
What should I pass in `setAttribute()` ?

Cheers,

**Comment by Mesuva** [comment]
I've not tried this myself, but I would try setting as the second argument to setAttribute an array of page IDs.

**Comment by eskema** [comment]
An array of cIDs worked perfectly. Thank you.
