### ISSUE TITLE
Use on page with 8.3.x?

### ISSUE THREAD

**Issue by dutchwave** [Mesuva/multi_page_selector_attribute#5]
Trying to fetch the pages on a page, but getting the error: Cannot use object of type Concrete\Core\Page\Page as array

Using this code:
```
products = $c->getAttribute('products', 'pageLinkArray');

if (!empty($products)) { 
   echo '<ul>';
   foreach($products as $prod) {
       echo '<li><a href="' . $prod['url'] . '">'. $prod['name']. '</a></li>';
   }
   echo '</ul>';
}
```

**Comment by Mesuva** [comment]
I've not used this attribute yet on a v8 site myself.
I may not have a chance to debug this for a while, so in the meantime I'd suggest just using:
$products = $c->getAttribute('products');

and looking over the pages, treating them as Page objects, so doing things like $prod->getCollectionName()

**Comment by dutchwave** [comment]
Thanks, that does the trick!
